puts("enter a color")
color = gets.chomp()
puts("enter a plural_noun")
plural_noun = gets.chomp()
puts("enter a celebrity")
celebrity = gets.chomp()

puts ("Roses are " + color)
puts(plural_noun +" are blue")
puts("I love " + celebrity)